create or replace trigger sysadm.PERS_NID_TR
AFTER INSERT OR UPDATE OR DELETE ON sysadm.PS_PERS_NID
FOR EACH ROW
DECLARE
V_AUDIT_OPRID VARCHAR2(64);
BEGIN
NULL;
END PERS_NID_TR;

CREATE OR REPLACE TRIGGER SYSADM.DEGREE 
AFTER LOGON ON SYSADM.SCHEMA
declare
sql_stmt    VARCHAR2(200);
BEGIN
    
    sql_stmt := 'ALTER SESSION FORCE PARALLEL DML PARALLEL 8';
    EXECUTE IMMEDIATE sql_stmt;
    sql_stmt := 'ALTER SESSION FORCE PARALLEL QUERY PARALLEL 8';
    EXECUTE IMMEDIATE sql_stmt;
END;

alter trigger "SYSADM"."DEGREE" enable;
